[package]
name = "rust-p2p-iroh"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
iroh = "0.32.1"
iroh-base = "0.32.0"
rand = "0.8"
tokio = "1.43.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
